testing

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -1,6 +1,13 @@
-
-
 name: Build & Test Services
+
+  #on:
+  #  push:
+  #    branches:
+  #      - 'ft/*'
+  #      - dev
+  #  pull_request:
+  #    branches:
+  #      - main
 
 on:
   workflow_call:
@@ -15,23 +22,41 @@ permissions:
 
 jobs:
   build-test:
+    #if: ${{ inputs.changed-services != '[]' && inputs.changed-services != '' }}
     runs-on: ubuntu-latest
+
+      #  strategy:
+      #    fail-fast: false
+      #    matrix:
+      #      service: ${{ fromJson(inputs.changed-services) }}
 
     strategy:
       fail-fast: false
       matrix:
-        service: ${{ fromJson(inputs.changed-services) }}
+        service: [
+          gateway-service,
+          nickname-service,
+          personal-user-service,
+          personal-transaction-service,
+          QRtoPay
+          ]
 
     env:
-      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}   # correct secret
-      AWS_REGION: ${{ secrets.AWS_REGION }}
+      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }} 
+      ECR_REPOSITORY: userbanking/${{ matrix.service }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      AWS_REGION: ${{ secrets.AWS_REGION }}
+
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 
 
-      - uses: actions/setup-java@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
@@ -41,6 +66,15 @@ jobs:
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+            #- name: Configure AWS credentials
+            #  continue-on-error: true
+            #  uses: aws-actions/configure-aws-credentials@v2
+            #  with:
+            #    role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }} 
+            #    aws-region: ${{ secrets.AWS_REGION }} 
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v5.1.0
@@ -51,29 +85,112 @@ jobs:
 
       - name: Build & Test
         working-directory: app/${{ matrix.service }}
-        run: mvn -B clean install
+        run: |
+          mvn -B clean install
 
       - name: Build Docker image
         id: build_image
         working-directory: app/${{ matrix.service }}
         run: |
           IMAGE_TAG=${{ github.sha }}
-          REPO="userbanking/${{ matrix.service }}"
-          IMAGE_NAME="$ECR_REGISTRY/$REPO:$IMAGE_TAG"
+          IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           docker build -t $IMAGE_NAME .
           echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
+     
+          #  - name: Build Docker image
+          #    id: build_image
+          #    working-directory: app/${{ matrix.service }}
+          #    run: |
+          #      IMAGE_TAG=${{ github.sha }}
+          #      IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          #      echo "Building image: $IMAGE_NAME"
+          #      docker build -t $IMAGE_NAME .
+          #      echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
 
-      - name: Login to ECR
+          #- name: Scan Docker image with Trivy
+          #  uses: aquasecurity/trivy-action@master
+          #  with:
+          #    image-ref: '${{ steps.build_image.outputs.image_name }}'
+          #    format: 'table'
+          #    exit-code: '1'
+          #    ignore-unfixed: true
+          #    vuln-type: 'os,library'
+          #    severity: 'CRITICAL,HIGH'
+
+          #- name: Push Docker image to ECR
+          #  #if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' || github.ref_name == 'main' }}
+          #  run: |
+          #    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
+          #    docker push ${{ steps.build_image.outputs.image_name }}
+
+
+      - name: Login to Amazon ECR
         run: |
           aws ecr get-login-password --region $AWS_REGION \
-          | docker login --username AWS --password-stdin $ECR_REGISTRY
+                | docker login --username AWS --password-stdin $ECR_REGISTRY
 
-      - name: Push Docker image
+
+      - name: Push Docker image to ECR
+        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main') }}
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
+          ECR_REPOSITORY: ${{ matrix.service }}
         run: |
-          docker push ${{ steps.build_image.outputs.image_name }}
+          IMAGE_NAME=${{ steps.build_image.outputs.image_name }}
+          echo "Pushing image: $IMAGE_NAME"
+          docker push $IMAGE_NAME
 
       - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
           name: ${{ matrix.service }}-image
           path: app/${{ matrix.service }}/
+
+
+  # local-k8s-test:
+  #   needs: build-test
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       service: ${{ fromJson(inputs.changed-services) }}
+        
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v4
+
+  #   - name: Set up KinD Cluster
+  #     uses: helm/kind-action@v1.5.0
+
+  #   - name: Set up Helm
+  #     uses: azure/setup-helm@v3
+  #     with:
+  #       version: v3.9.0
+
+  #   - name: Load Docker Image into KinD Cluster
+  #     run: |
+  #       IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
+  #       kind load docker-image $IMAGE_NAME
+
+  #   - name: Install Sealed Secrets
+  #     run: |
+  #       helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
+  #       helm install sealed-secrets sealed-secrets/sealed-secrets -n kube-system --create-namespace
+
+  #   - name: Test Sealed Secrets
+  #     run: |
+  #       kubectl create secret generic mysecret --dry-run=client --from-literal=password=supersecret -o json > mysecret.json
+  #       kubeseal --format=yaml < mysecret.json > mysealedsecret.yaml
+  #       kubectl apply -f mysealedsecret.yaml
+  #       kubectl get sealedsecret mysecret
+
+  #   - name: Deploy with Helm
+  #     working-directory: app/${{ matrix.service }}/helm
+  #     run: |
+  #       helm install ${{ matrix.service }}-release . --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY --set image.tag=${{ github.sha }}
+
+  #   - name: Verify Deployment
+  #     run: |
+  #       kubectl wait --for=condition=available deployment/${{ matrix.service }}-release --timeout=120s
+  #       kubectl get pods
